from setuptools import setup

setup(name="gdsclient",
      version="2.0.1",
      description="GeoDataspace Client for creating geounits",
      long_description=open("README.md").read(),
      author="Sumanth Mannam, Tanu Malik, Danko Adrovic",
      author_email="tanu@cdm.depaul.edu",
      url="https://github.com/globusonline/catalog-client",
      install_requires=['leveldb>=0.193','configparser>=3.3.0r2', 'docker-py>=1.2.2', 'nose>=1.2.1'],
      packages=["geodataspace",
                "geodataspace.client",
                "geodataspace.client.datastore",
                "geodataspace.client.commands",
                "geodataspace.client.util",
                "geodataspace.client.tests"],
      package_data={},
      scripts=["geodataspace/client/gdsclient.py"],
      keywords=["geodataspace","globusonline"],
      classifiers=[
          "Development Status :: 3 - Alpha",
          "Intended Audience :: Users",
          "License :: OSI Approved :: Apache Software License",
          "Operating System :: MacOS :: MacOS X",
          "Operating System :: Microsoft :: Windows",
          "Operating System :: POSIX",
          "Programming Language :: Python",
          "Topic :: Communications :: File Sharing",
          "Topic :: Internet :: WWW/HTTP",
          "Topic :: Software Development :: Libraries :: Python Modules",
          ],
      )
